# access log
quarkus.http.access-log.enabled=true
quarkus.http.access-log.log-to-file=false
quarkus.http.access-log.rotate=false

quarkus.log.category."io.quarkus.http.access-log".level=INFO
quarkus.log.category."io.quarkus.http.access-log".use-parent-handlers=false
quarkus.log.category."io.quarkus.http.access-log".handlers=access-log-handler

quarkus.log.handler.file.access-log-handler.enable=true
quarkus.log.handler.file.access-log-handler.path=logs/access.log
quarkus.log.handler.file.access-log-handler.format=%s%n
quarkus.log.handler.file.access-log-handler.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.handler.file.access-log-handler.rotation.rotate-on-boot=false
